### ISSUE TITLE
How would we retrive multiple entries?

### ISSUE THREAD

**Issue by ohbob** [tr1ckydev/great.db#2]
How would we retrieve multiple entries from db? Modified example down bellow. 

```ts
import { DataType, GreatDB, Schema } from "great.db";

// Creating the database
const db = new GreatDB.Database({
    type: GreatDB.Type.Disk,
    name: "test"
});

// Creating the schema and the table (Typescript types are automagically inferred)
const customerSchema = Schema.Create({
    id: DataType.AutoIncrement,
    name: DataType.String,
    phone: DataType.Number,
    address: DataType.String,
    member: DataType.Boolean
});
const table = db.table("customers", customerSchema);

// Populating the table
await table.set([
    {
        name: "John Doe",
        phone: 1234567890,
        address: "Obere Str. 57",
        member: false
    },
    {
        name: "Adam Evans",
        phone: 6789067890,
        address: "120 Hanover Sq.",
        member: true
    },
    {
        name: "Frank Smith",
        phone: 1234512345,
        address: "City Center Plaza 516 Main St.",
        member: true
    }
]);

// Retrieving multiple values
const x = await table.get("member", true);
console.log(x?.name);   // Adam Evans, <-- but where is Frank Smith?

// Closing the database after all tasks are done
db.close();
```

**Comment by tr1ckydev** [comment]
Thanks for reporting, will be fixed in the next update soon.
So in the next update the set() will accept a third optional parameter called fetchAll which will be by default false and the function will return the first row, else if true it will return the results in an array. The return type of the function (typescript one) will also be correctly returning the type based on what the fetchAll value is.

**Comment by ohbob** [comment]
So if the default false returned 1 entry, true would return all entries, how could we filter out to not get more than n amount ? In terms of reading the DB, e.g. 500 million entries, I guess it would be wise to be able to set the return array limit and the reading length, so we could read e.g. 50k entries, not all 500 million. Hope that makes sense.

**Comment by tr1ckydev** [comment]
I was about to explain about this in my previous reply. get() won't be changed any further, it will return all.
Instead a new powerful filter() function is coming in the next update through which all this can be done such as limit, user specified condition to query data, count and a lot more.

**Comment by ohbob** [comment]
awesome, looking forward to it!
